export const colorVariants = {
  solid: {
    default: "bg-default text-default-foreground",
    foreground: "bg-foreground text-background",
    primary: "bg-primary text-primary-foreground",
    secondary: "bg-secondary text-secondary-foreground",
    success: "bg-success text-success-foreground",
    warning: "bg-warning text-warning-foreground",
    danger: "bg-danger text-danger-foreground",
  },
  bordered: {
    default: "border-default text-default-foreground",
    foreground: "border-foreground text-foreground",
    primary: "border-primary text-primary",
    secondary: "border-secondary text-secondary",
    success: "border-success text-success",
    warning: "border-warning text-warning",
    danger: "border-danger text-danger",
  },
  light: {
    default: "bg-default-50 text-default-600",
    foreground: "bg-foreground-50 text-foreground-600",
    primary: "bg-primary-50 text-primary-600",
    secondary: "bg-secondary-50 text-secondary-600",
    success: "bg-success-50 text-success-600",
    warning: "bg-warning-50 text-warning-600",
    danger: "bg-danger-50 text-danger-600",
  },
  flat: {
    default: "bg-default-100 text-default-700",
    foreground: "bg-foreground-100 text-foreground-700",
    primary: "bg-primary-100 text-primary-700",
    secondary: "bg-secondary-100 text-secondary-700",
    success: "bg-success-100 text-success-700",
    warning: "bg-warning-100 text-warning-700",
    danger: "bg-danger-100 text-danger-700",
  },
  faded: {
    default: "bg-default-50 text-default-600",
    foreground: "bg-foreground-50 text-foreground-600",
    primary: "bg-primary-50 text-primary-600",
    secondary: "bg-secondary-50 text-secondary-600",
    success: "bg-success-50 text-success-600",
    warning: "bg-warning-50 text-warning-600",
    danger: "bg-danger-50 text-danger-600",
  },
  shadow: {
    default: "bg-background text-foreground shadow-lg",
    foreground: "bg-foreground text-background shadow-lg",
    primary: "bg-primary text-primary-foreground shadow-lg",
    secondary: "bg-secondary text-secondary-foreground shadow-lg",
    success: "bg-success text-success-foreground shadow-lg",
    warning: "bg-warning text-warning-foreground shadow-lg",
    danger: "bg-danger text-danger-foreground shadow-lg",
  },
}; 